### ISSUE TITLE
Any plans on making a playlist or the ability to select a folder?

### ISSUE THREAD

**Issue by jpwhitney** [keredson/gnomecast#65] opened 2018-08-11 01:21 UTC
This would be a great feature!

**Comment by didierga** [comment] 2018-08-15 17:28
I suggest two improvement in this area:
- gnomecast should start in user folder and not in recent folder
- if a first file is opened in a chosen directory, gnomecast should use the same directory for a subsequent open

**Comment by ygmarchi** [comment] 2018-09-01 20:17
I'd love this feature

**Comment by ygmarchi** [comment] 2018-09-05 00:09
The attached script menages to cast the content of the current directory


[cast_dir.zip](https://github.com/keredson/gnomecast/files/2350672/cast_dir.zip)

**Comment by ajkothari13** [comment] 2018-09-06 09:32
@ygmarchi , Hi. Linux-noob and ametuer techie here. How to use this script you posted?

**Comment by ygmarchi** [comment] 2018-09-06 09:57
It's not a refined thing... 

You should open a terminal in the directory containing the media files you want to open (the script is recursive on subdirectories) and launch it with the python interpreter (python3)

I have also managed to add it to Nautilus (Gnome file explorer) as a right mouse button option (search Google for how to do it).

Actually there's also a patch you need to apply to the python pychromecast library because of a bug regarding multiple files execution. Details here:  https://github.com/balloob/pychromecast/issues/225

**Comment by ygmarchi** [comment] 2018-09-06 09:59
You need also to customize the three variables at the top of the script

host='192.168.1.90' #you computer ip address (may/should be obtained dinamically)
port=str(8000)         #the port to listen to (may/should be obtained dinamically)
subtype='flac'          #the type of media to server (may/should be obtained dinamically)

**Comment by ajkothari13** [comment] 2018-09-06 11:00
Thanks @ygmarchi . Making changes to library, then compiling etc are beyond my skill level. But you took time to reply and help for that I am very grateful. Hope your given information helps someone else.

**Comment by ygmarchi** [comment] 2018-09-06 11:16
There's no compilation, it's a script.

The file should be under /usr/lib/python3/dist-packages/pychromecast
/controllers/media.py

You may try to add my lines after the line
self.last_updated = datetime.utcnow()

in the update method.
Best regards, Carlo.

Il gio 6 set 2018, 13:00 ajkothari13 <notifications@github.com> ha scritto:

**Comment by keredson** [comment] 2018-09-06 15:40
i'm open to this.  i'm not sure how the UI would work tho.

- would there be a side panel w/ the queued videos?  or inline vertically?  (vertically i think would look better, but i've already had one complaint he UI is too tall for 768px tall screens)
- would you be able to pre-select subtitles for each of the items in the queue?  or only the current playing video?

**Comment by ygmarchi** [comment] 2018-09-06 15:49
I think the need to play multiple files is mostly felt for audio tracks with the Chromecast dongle.

**Comment by e-ht** [comment] 2018-09-06 17:32
@ygmarchi also when I'm binging on an entire season of Friends...

**Comment by keredson** [comment] 2018-09-06 21:33
all right, i think this actually works.  anyone want to give it a whirl?  branch `file-queue`.

![image](https://user-images.githubusercontent.com/2049665/45186291-cd9a4e80-b1e1-11e8-8412-135915434a8d.png)

**Comment by ajkothari13** [comment] 2018-09-07 11:36
@ygmarchi Thanks for taking time to help. Again!

**Comment by ajkothari13** [comment] 2018-09-07 11:38
@keredson Hi. Thanks for providing much needed feature! Is this feature merged in the main software? If i try "pip3 install gnomecast", will this change appear?

**Comment by ajkothari13** [comment] 2018-09-07 12:15
I had selected 200 songs to play. The app is crashing (and disappearing from screen) after playing just 1 song. Is there any other information that could be shared?

**Comment by keredson** [comment] 2018-09-07 14:13
@ajkothari13 not merged, this was a pretty big code change, want to test more.  :)  thanks for helping!

btw you can test it w/o blowing away your current version by:
```
$ git clone https://github.com/keredson/gnomecast.git
$ cd gnomecast
$ git checkout file-queue
$ python3 gnomecast.py
```

if you run it in a terminal via `python3 gnomecast.py` when it crashes it should show an exception.  can you post that here?

**Comment by keredson** [comment] 2018-09-07 19:31
1. i don't see how.  code should be identical.
2. i don't transcode audio at all, assuming it's a supporting format `('aac','mp3','wav')`.  what is the file and how do you know it's 120kb?

**Comment by ajkothari13** [comment] 2018-09-08 04:06
1. Will try again, today. May be i am doing something wrong. Will confirm and inform.
2. I opened gnomecast.py on terminal and saw this. Now that you say, I am not sure what I saw is a lowered bitrate. Attaching a screenshot.
![bitrate](https://user-images.githubusercontent.com/35865290/45250131-af039700-b34a-11e8-9402-326ff7328400.png)

**Comment by keredson** [comment] 2018-09-08 20:55
yep.  flac file, that's why.  shouldn't need to transcode that at all.  will fix, thanks.

**Comment by keredson** [comment] 2018-09-09 01:46
i take it back.  flac as a codec is supported, but not as a container.

also i suspect that bitrate shown is the "video" bitrate (it's being transcoded into an mp4 file w/ an mp3 audio track).  NOT the audio bitrate.

yes, confirmed, video bitrate.  ffmpeg audio bitrate is defaulting to 128kb/s.

i tried doing an ffmpeg "copy" of the flac stream into an audio track of an mp4 container, but it didn't work.  (my home mini refused to play it at least.)

making code change to force it to 256kb/s.

**Comment by ygmarchi** [comment] 2018-09-13 19:44
I'm trying the file-queue version.
It seems to work very well, thank you very much.

Maybe I would position the 'Add one or more files...' button before the list. That's my taste, but I think it makes sense because you use it before the list.

I would also give a more immediate evidence of the playing track, for example placing the title in the window title.

Also I would not convert flac files before playing because they should be supported as is, but I see there's already a discussion open about this.

**Closed** 2018-09-27 20:02 UTC

**Comment by keredson** [comment] 2018-09-27 20:05
i made some more UI improvements (notably around the calculation of the height of the table, and it's visibility.)  all for further ui tweaks, but it's been running for me w/o issue for a bit, so i pushed it.  1.5.0 in pip.  :)
